---
name: build
on: [deployment, push]

jobs:
  github-container-registory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          build-args: |
            USERNAME=tomonori
            GIT_USER_EMAIL=${{ secrets.GIT_USER_EMAIL }}
            GIT_USER_NAME=${{ secrets.GIT_USER_NAME }}
          context: .
          file: Dockerfile
          load: true
          tags: molecule:preview

      - name: Get Ansible version
        id: ansible_version
        run: |
          tag=$(docker run --rm molecule:preview ansible --version | awk 'NR==1 {print $2}')
          echo "tag=${tag}" >> $GITHUB_OUTPUT

      - name: Get Ansible lint version
        id: ansible_lint_version
        run: |
          tag=$(docker run --rm molecule:preview ansible-lint --version | awk 'NR==1 {print $2}')
          echo "tag=${tag}" >> $GITHUB_OUTPUT

      - name: Get Molecule version
        id: molecule_version
        run: |
          tag=$(docker run --rm molecule:preview molecule --version | awk 'NR==1 {print $2}')
          echo "tag=${tag}" >> $GITHUB_OUTPUT

      - name: Build and push 1
        uses: docker/build-push-action@v3
        with:
          build-args: |
            USERNAME=tomonori
            GIT_USER_EMAIL=${{ secrets.GIT_USER_EMAIL }}
            GIT_USER_NAME=${{ secrets.GIT_USER_NAME }}
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/docker-images-mamono210/ansible-tools:latest

      - name: Build and push 2
        uses: docker/build-push-action@v3
        with:
          build-args: |
            USERNAME=tomonori
            GIT_USER_EMAIL=${{ secrets.GIT_USER_EMAIL }}
            GIT_USER_NAME=${{ secrets.GIT_USER_NAME }}
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/docker-images-mamono210/ansible-tools:ansible${{ steps.ansible_version.outputs.tag }}ansible-lint${{ steps.ansible_lint_version.outputs.tag }}molecule${{ steps.molecule_version.outputs.tag }}

  trailing-whitespace:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harupy/find-trailing-whitespace@56310d70ae8fd21afec8d4307d2d9ab6c15e7c5d

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@665205c3255fcf157ef8dc9a40d527fe025a4bc8
        with:
          config_file: .yamllint
